scaredyCat.ui.artWork = (function () {
	"use strict";
	var scarecrow, bird;
	scarecrow = "                    __  __\n";
	scarecrow += "                  /_ _^^_ _\\\n";
	scarecrow += "             _____|________|______\n";
	scarecrow += "            `=====.'\"\"\"\"\"\"'.=====`\n";
	scarecrow += "                 / /a    /a \\   .-.\n";
	scarecrow += "                |     /\\     | <\"  )\n";
	scarecrow += "                \\            /  /  \\\n";
	scarecrow += "   .`\\,         _'. \\/\\/\\/ .'_  \\ \\_\\  ./,'\n";
	scarecrow += "   '-.\\'-------'  \\`------'/  '--\"\"---'//.-'\n";
	scarecrow += "###'.-'/________    \\/\"\"\"\"\\/    ________\\'-.'###\n";
	scarecrow += "    '/`         \\      :       /         `\\`\n";
	scarecrow += "                 |            |\n";
	scarecrow += "                 \\     :      |\n";
	scarecrow += "                 |            \\\n";
	scarecrow += "                 \\_____:_____ /\n";
	scarecrow += "                  [I=I=[_]I=I]\n";
	scarecrow += "                 /    |       \\\n";
	scarecrow += "                /     |_       \\\n";
	scarecrow += "               /       /\\       \\\n";
	scarecrow += "              /       /##\\       \\\n";
	scarecrow += "              |     ,/ ## \\,     |\n";
	scarecrow += "               \\    \\  ##  /    /\n";
	scarecrow += "                \\    \\ ## /    /\n";
	scarecrow += "                 \\    \\##/    /\n";
	scarecrow += "                  \\   /\\/\\   /\n";
	scarecrow += "                __,\\_/X##X\\_/.__\n";
	scarecrow += "                '.'/|\\\\XX//|\\'.`\n";
	scarecrow += "                 '/'|.\\##/,|`\\'\n";
	scarecrow += "                       ##\n";
	scarecrow += "                       ##\n";
	scarecrow += "                       ##\n";
	scarecrow += "                    \\  ## /     /\n";
	scarecrow += "           \\ ,    \\  \\\\##// , / /,   /.\n";
	scarecrow += "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'\n";
	bird = '             __,---,\n';
	bird += '   .---.     /__|o\\  )    .-"-.      .----.""".\n';
	bird += '  /   6_6     `-\\ / /    / 4 4 \\    /____/ (0 )\\\n';
	bird += '  \\_  (__\\     ,) (,     \\_ v _/      `--\\_    /\n';
	bird += '  //   \\       //   \\    //   \\         //   \\\n';
	bird += ' ((     ))    {(     )} ((     ))       {{     }}\n';
	bird += '==""===""======""===""===""===""=========""===""=======\n';
	bird += '    |||         |||||      |||             |||\n';
	bird += '     |           |||        |               | \n';
	bird += '     |';
}());